### ISSUE TITLE
archive this project

### ISSUE THREAD

**Issue by sambao21** [cerner/github_bot-ruby#10]
Is this project active? Can we archive this project? By archiving, previously release assets will be untouched, but support will cease for this project going forward. If anyone has any reasons this project should not be archived, please comment by March 1st.

**Comment by poloka** [comment]
Yes, this project is active and utilized by all ruby based bots developed within OHAI.

**Comment by sambao21** [comment]
As discussed in email. Will archive this in public github, and this project can be forked and continue internally as desired.
